name: testproductcatalog
description: Product catalog test

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1

  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  dartz: ^0.8.9
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  get_it: ^4.0.0
  connectivity: ^0.4.8+1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  data_connection_checker: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.8.0

flutter:
  uses-material-design: true
